[package]
name = "binarius"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.4"
nix = { version = "0.29.0", features = ["fanotify", "dir"] }
